name: Python package

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # checks all of the versions allowed in pyproject.toml
        python-version: ["3.10", "3.11"]

    steps:
      # installs python
      # one execution of the tests per version listed above
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      # installs poetry
      - uses: Gr1N/setup-poetry@v8
      - name: Python Poetry Action
        run: |
          poetry install
      - name: Run tox
        run: |
          poetry run tox
