name: Code quality checks

on:
  workflow_call:
  pull_request:
  push:
    branches:
      - master

jobs:
  lint-test:
    name: API linting, formatting, and tests
    runs-on: ubuntu-latest
    steps:
      # set up python
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # install poetry
      - uses: Gr1N/setup-poetry@v8

      - name: Install analytics package using poetry
        run: make install

      - name: Run linting
        run: make lint

      - name: Run tests
        run: make test-audit
